version: '3.8'

services:
  slim.test:
    build:
      context: ../../nginx-reverse-proxy/
      dockerfile: ./php7/Dockerfile
    image: proxyapp/php7.4
    restart: always
    volumes:
      - .:/var/www/html
    environment:
      - WWWUSER=${WWWUSER}
      - WWWGROUP=${WWWGROUP}
      - VIRTUAL_HOST=slim.test
      - NETWORK_ACCESS=internal

networks:
  default:
    external: true
    name: www-proxy-net

