version: '3.8'

services:
  laravel9.test:
    build:
      context: ../../nginx-reverse-proxy/
      dockerfile: ./php8/Dockerfile
    image: proxyapp/php8.2
    restart: always
    volumes:
      - .:/var/www/html
    environment:
      - WWWUSER=${WWWUSER}
      - WWWGROUP=${WWWGROUP}
      - VIRTUAL_HOST=laravel9.test
      - NETWORK_ACCESS=internal

networks:
  default:
    external: true
    name: www-proxy-net


